# Add upper toolbar positions in CMC
positions = {
    "st": [(493, 114), (564, 144)],
    "fl": [(493, 114), (559, 172)],
    "conf": [(493, 114), (579, 229)],
    "check": [(412, 108), (482, 241)],
    "reset": [(412, 108), (440, 144)],
    "svc": [(576, 113)],
    "rl": [(1901, 582)],
}

# Add Paths which you want to navigate on host machine in CMC
path_commands = {
    "lp": "%IBERDIR%/LANProxy/LanProxy",
    "temp": "c:\\temp",
    "panda": "c:\\ProgramData\\Panda Security\\Panda Aether Agent\\Downloads",
    "proxyboh": "c:\\CMCLanDesk\\NSS LANProxy",
    "proxyterm": "c:\\CMCLanDesk\\NSS LANProxy Handler",
    "programdata": "c:\\ProgramData",
    "programfiles": "c:\\program files (x86)",
    "cmc": "C:\\Program Files\\NCR\\CMC",
    "pslogs": "C:\\Windows\Temp\PSInfo",
}

# Add commands here that you want to type in CMD of CMC
shell_commands = {
    "restartpanda1": "tasklist /svc | findstr PandaAetherAgent",
    "restartpanda2": "taskkill /f /pid ",
    "tls": "C:\\temp\\TLSEnable.bat",
    "psrepair": r"""IF EXIST "C:\\Program Files\\Panda Security\\Panda Aether Agent\\Additional files\\PSInfo.exe" ("C:\\Program Files\\Panda Security\\Panda Aether Agent\\Additional files\\PSInfo.exe" -d:"[AETHERUPDATE FULL]" -repair /nogui) ELSE ("C:\\Program Files (x86)\\Panda Security\\Panda Aether Agent\\Additional files\\PSInfo.exe" -d:"[AETHERUPDATE FULL]" -repair /nogui)""",
    "reboot": "shutdown.exe -r -f -t 03",
    "ps": r"""IF EXIST "C:\\Program Files\\Panda Security\\Panda Aether Agent\\Additional files\\PSInfo.exe" ("C:\\Program Files\\Panda Security\\Panda Aether Agent\\Additional files\\PSInfo.exe" -d:"[AETHERUPDATE FULL]" /nogui) ELSE ("C:\\Program Files (x86)\\Panda Security\\Panda Aether Agent\\Additional files\\PSInfo.exe" -d:"[AETHERUPDATE FULL]" /nogui)""",
    "vncenablefs": r'''powershell -Command "$path='C:\\Program Files\\NCR\\CMC\\pvnc.ini'; $content=Get-Content $path; $adminFound=$false; $inserted=$false; $newContent=@(); foreach ($line in $content) { if ($line -match '^\[admin\]$') { $adminFound=$true; $newContent+= $line; continue }; if ($adminFound -and $line -match '^FileTransferEnabled\s*=\s*0$') { $newContent+= 'FileTransferEnabled=1'; $inserted=$true; continue }; if ($adminFound -and $line -match '^FileTransferEnabled\s*=\s*1$') { $inserted=$true }; $newContent+= $line }; if ($adminFound -and -not $inserted) { $updatedContent=@(); foreach ($line in $newContent) { $updatedContent+= $line; if ($line -match '^\[admin\]$') { $updatedContent+= 'FileTransferEnabled=1' } }; Set-Content $path -Value $updatedContent } else { Set-Content $path -Value $newContent }"''',
    "vncdisablefs": r'''powershell -Command "$path='C:\\Program Files\\NCR\\CMC\\pvnc.ini'; $content=Get-Content $path; $adminFound=$false; $inserted=$false; $newContent=@(); foreach ($line in $content) { if ($line -match '^\[admin\]$') { $adminFound=$true; $newContent+= $line; continue }; if ($adminFound -and $line -match '^FileTransferEnabled\s*=\s*1$') { $newContent+= 'FileTransferEnabled=0'; $inserted=$true; continue }; if ($adminFound -and $line -match '^FileTransferEnabled\s*=\s*0$') { $inserted=$true }; $newContent+= $line }; if ($adminFound -and -not $inserted) { $updatedContent=@(); foreach ($line in $newContent) { $updatedContent+= $line; if ($line -match '^\[admin\]$') { $updatedContent+= 'FileTransferEnabled=0' } }; Set-Content $path -Value $updatedContent } else { Set-Content $path -Value $newContent }"''',
    "ppstemp": 'C:\\temp\\nss\\psinfo.exe -d:"[AETHERUPDATE FULL]" /nogui',
    "pendpoint": "c:\\temp\\nss\\EndpointAgentTool.exe /cfg /su /s /d /c /ku",
    "psetproxy": "c:\\temp\\nss\\setproxyallusers.bat ",
    "pcertinst": "C:\\Temp\\nss\\CertCheck\\CertCheck /add /ca && C:\\Temp\\nss\\CertCheck\\WESCertcheck /add /ca",
    "pwginst": 'msiexec /i "c:\\temp\\nss\\WatchGuard Agent.msi" /qn /L*V "c:\\temp\\nss\\WatchGuardAgent.log"',
    "checkproxy": "netsh winhttp show proxy",
    "endpoint": "c:\\temp\\EndpointAgentTool.exe /cfg /su /s /d /c /ku",
    "ip": "ipconfig /all",
    "wginst": 'msiexec /i "c:\\temp\\WatchGuard Agent.msi" /qn /L*V "c:\\temp\\WatchGuardAgent.log"',
    "setproxy": "c:\\temp\\setproxyallusers.bat ",
    "wgproxy": "c:\\temp\\wgsetproxyallusers.bat",
    "mkdir": "mkdir c:\\temp",
    "sys": "systeminfo",
    "arp": "arp -a",
    "certinst": "C:\\Temp\\CertCheck\\CertCheck /add /ca && C:\\Temp\\CertCheck\\WESCertcheck /add /ca",
    "lpinst": "%IBERDIR%\\LANProxy\\LANProxy\\InstallLANProxy.bat",
    "pstemp": 'C:\\temp\\psinfo.exe -d:"[AETHERUPDATE FULL]" /nogui',
    "tlsfix": "c:\\temp\\tlsfix.exe",
    "lpremove": 'taskkill /f /im lanproxy.exe && sc config lanproxy start= disabled && sc delete lanproxy & rmdir /s /q "%LOCALDIR%\\EPS" & rmdir /s /q "%LOCALDIR%\\LANProxy"',
    "host": "hostname",
    "restart panda": "net stop PandaAetherAgent && net start PandaAetherAgent",
    "sys": "systeminfo",
    "checkbit": 'systeminfo | findstr /i /c:"System Type"',
    "checksha": r"""wmic qfe where "HotFixID='KB3140245' or HotFixID='KB4474419'" get HotFixID, InstalledOn""",
    "checktls": 'reg query "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.2\\Client"',
    "cleanpanda": r'''powershell -Command "foreach ($F in @('C:\\Program Files\\Panda Security','C:\\Program Files (x86)\\Panda Security','C:\\ProgramData\\Panda Security')) { if (Test-Path $F) { try { Remove-Item -LiteralPath $F -Recurse -Force -ErrorAction Stop; Write-Host 'Deleted: ' $F } catch { Write-Host 'Not deleted: ' $F ' - ' $_.Exception.Message } } else { Write-Host 'Not found: ' $F } }"''',
    "cleantemp": 'del /q "C:\\temp"',
    "sha1": "wusa.exe c:\\temp\\kb4474419.msu /quiet /norestart /log:c:\\temp\\kb4474419.log",
    "sha2": "wusa.exe c:\\temp\\kb3140245.msu /quiet /norestart /log:c:\\temp\\kb3140245.log",
    "redist32": "C:\\temp\\vcredist2015_2017_2019_2022_x86 /quiet /norestart",
    "redist64": "C:\\temp\\vcredist2015_2017_2019_2022_x64 /quiet /norestart",
    "proxy32term": "c:\\temp\\NSSProxySetup_32bit.exe -device_type=term -host=ALOHABOH -port=9180 -fallback_ip=",
    "proxy64term": "c:\\temp\\NSSProxySetup_64bit.exe -device_type=term -host=ALOHABOH -port=9180 -fallback_ip=",
    "proxy64boh": "c:\\temp\\NSSProxySetup_64bit.exe -device_type=boh -port=9180 -offline",
    "ldremove1": '"%programfiles%\\landesk\\ldclient\\vulscan.exe" /removehips /rebootaction=never',
    "ldremove2": "c:\\temp\\UninstallWinClient20173.exe /forceclean /noreboot",
    "getkeyname": "sc getkeyname ",
}
